tensorflow/model-optimization

setup.py

This is also how TensorFlow handles it: https://github.com/tensorflow/tensorflow/blob/6c8cbdceccce20f886a08b0cf00ac2e783ac524c/tensorflow/tools/pip_package/setup.py#L56

Only install enum34 for Python <= 3.4

---

tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py

This PR fixes a bug in `ClusterWrapper` that we came across when attempting to strip a selectively clustered model. In this particular use case we do not yet have access to `layer.weights` in `ClusterWrapper.__init__()`, therefore `self.weights_num` will end up being 0. This attribute was then used in `_strip_clustering_wrapper()` as the range of a for loop and thus we ended up skipping the weights. The fix removes the `self.weights_num` attribute and instead relies on `len(layer.restore)` in the stripping method.
The PR contains the bug fix itself, as well as a new unit tests for the selective clustering.

Fix bug in ClusterWrapper affecting stripping a selectively clustered model

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py

This PR further improves the test coverage of selective clustering. It contains the following changes:
- Renamed `testClusterLayersSelectively()` to `testClusterSequentialModelSelectively()` to better reflect the precise use case being tested
- Added new unit test `testClusterFunctionalModelSelectively()` to cover the previously untested use case of selectively clustering a functional model
- Added `@tf_test_util.run_in_graph_and_eager_modes` annotation to all selective clustering unit tests in order to ensure that they are run in both modes

Improvements for selective clustering unit tests

---

tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py

This PR fixes an inconsistency (bug) in the return type of `get_clusterable_weights()` between built-in RNN cells and custom `ClusterableLayer` objects. Though the docstring states that `get_clusterable_weights()` returns a `(name, kernel)` tuple, in case of RNN cells we only returned the kernel itself, without the name. This led to an inconsistent use of `get_clusterable_weights()` between custom clusterable layers and certain built-in Keras layers.

Fix inconsistency in return type of get_clusterable_weights()

---

tensorflow_model_optimization/python/core/clustering/keras/BUILD
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py

This PR addresses the proposal raised in [this comment](https://github.com/tensorflow/model-optimization/pull/125#discussion_r363539787) and moves `testValuesRemainClusteredAfterTraining()` from `cluster_wrapper_test.py` into a separate file named `cluster_integration_test.py`.

Move clustering end-to-end test into separate file

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py

This PR improves the documentation of the clustering tests by adding docstrings that explain what each test is supposed to verify.

Added docstrings to clustering tests

---

tensorflow_model_optimization/g3doc/guide/quantization/training.md

Fixes broken link added in 9b593b23c051406d2de72abbd31f42105967d4a0. The anchor link should be `general-support-matrix`.

Fix link to general support matrix anchor

---

tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py
tensorflow_model_optimization/python/core/clustering/keras/clusterable_layer.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py

This PR aims to remove private TF and Keras dependencies from the clustering API while maintaining compatibility with both TF 1.X and TF 2.0.

Remove private API dependencies from clustering

---

community/rfcs/techniques/design/20200306-weight-clustering-design.md
community/rfcs/techniques/proposals/20200205-weight-clustering-proposal.md

This PR introduces the clustering RFC document and replaces PR [#260](https://github.com/tensorflow/model-optimization/pull/260), which is now obsolete.

Clustering RFC

---

tensorflow_model_optimization/g3doc/guide/install.md

Hi,
This PR adds a note in the TensorFlow Model Optimization installation guide to recommend the usage of Python virtual environments in a way similar to the recommendation in the TensorFlow installation guide.

Recommend the usage of virtual environments in the TensorFlow Model Optimization installation guide

---

tensorflow_model_optimization/python/examples/sparsity/keras/imdb/imdb_lstm.py

tensorflow.python.keras.layers.LSTM() is not registered as prunableLayer,
change LSTM_example, using registerd tensorflow.keras.layers.LSTM()
version:
TF_MOT: tf-model-optimization-nightly-0.3.0.dev20200601
TF: 2.3.0-dev20200601

Use tf.keras.layers in LSTM pruning example.

---

tensorflow_model_optimization/python/core/clustering/keras/BUILD
tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_config.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids_test.py

This PR alters the configuration object used in weight clustering in accordance with the RFC proposal. It contains the following changes:
* Added enum `CentroidInitialization` to capture possible centroid initialization methods
* Configuration object modified to use this enum to specify the centroid initialization technique to be used (instead of the string-based descriptor used until this point)
* Updated serialization and unit tests accordingly

Improve configuration object for clustering API

---

tensorflow_model_optimization/python/core/clustering/keras/BUILD
tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py

This PR fixes a bug in strip_clustering() where cluster nodes remained in the model when exporting to saved_model format.

Added fix for issues with saved model in strip_custering()

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py

This is a small cleanup PR that removes some unused imports and definitions from `cluster_wrapper_test.py`.

Remove unused imports from cluster_wrapper_test

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py

Reflect clustered layer's name in new layer's name

---

tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_config.py

This PR improves the documentation of `cluster_config.CentroidInitialization` by moving the description of the various centroid initialization methods from the docstring of `cluster_weights()` to `CentroidInitialization`'s own docstring.

Add docstring for cluster_config.CentroidInitialization

---

tensorflow_model_optimization/python/core/api/clustering/__init__.py
tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py

This PR adds the clustering module to `python/core/api` and updates `build_docs.py` to generate the correct API documentation for clustering.

Add clustering module to API docs generator

---

tensorflow_model_optimization/g3doc/guide/clustering/clustering_comprehensive_guide.ipynb
tensorflow_model_optimization/g3doc/guide/clustering/clustering_example.ipynb

This PR adds the Jupyter notebook for clustering.

Create Jupyter notebook for clustering

---

tensorflow_model_optimization/g3doc/_book.yaml

This PR adds the relevant weight clustering documentation to `_book.yaml` in order to make them visible on the TFMOT site.
Note: This depends on https://github.com/tensorflow/model-optimization/pull/330

Add clustering overview document and Jupyter notebooks to _book.yaml

---

tensorflow_model_optimization/g3doc/guide/clustering/clustering_comprehensive_guide.ipynb

@alanchiao 
Fix https://github.com/tensorflow/model-optimization/issues/511

Fix incorrect header sizes in the clustering comprehensive guide

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_config.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids_test.py

Added Kmeans++ centroid initialization to the clustering API as an alternative configurable initialization method to density-based, linear and random.
Allowing the heuristic to determine the number of retries (num_retries_per_sample=-1) and a seed of 9 to match closely with the default scikit-learn kmeans++ implementation.
**Experimental results:**
| Model | Initialization | # of clusters | Top-1 accuracy (%) | Configuration | Size of compressed .tflite (MB) | 
| ------------- | ------------- |  ------------- |  ------------- | ------------- |------------- |
| MobileNetV2  |  Linear | 32 |  69.33  |  Full model (except DepthwiseConv2D layers) | 2.60 Mb|
| MobileNetV2  |  kmeans++ | 32 |  71.462%  |  Full model (except DepthwiseConv2D layers) | 3.13 Mb|
| MobileNetV2  |  Linear | …

Added kmeans++ initialization to clustering API

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py

In this PR we simplify clustering registry: if layer does not have weights, it is enabled for clustering automatically. Example of such layers: Reshape, Pooling, Maximum/Minimum.
This PR addressed problem with TensorFlowOpLayer from this [PR](https://github.com/tensorflow/model-optimization/pull/532) as well.
Added test for DepthwiseConv2D layer as well: we don't cluster it as an accuracy loss is big and can't be recovered during re-training.

[Clustering] Simplification of clustering registry.

---

tensorflow_model_optimization/python/core/clustering/keras/BUILD
tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_distributed_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py

This PR adds the support for `tf.distribute` after enabling the update of cluster indices. Since these variables are deterministic (they depend on weights but not batch inputs), they are set as SyncOnRead so that they are calculated in each replica independently. In the model exporting time, they will be read from the first replica. Hope in this way we can avoid unnecessary sync for large LUTs.
This PR should follow https://github.com/tensorflow/model-optimization/pull/519, and it tests the change in cluster indices in cross-replica context (in the unit test). That is why it contains two commits.

Add support for tf.distribute after enabling the update of cluster indices

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py

Small tidy up: removed variables that are not set and not used - some leftovers.

[Clustering] Small tidy up - removed unusued variables

---

tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py

In this PR we enable clustering for models with sub-models: all deep layers, that are supported for clustering, are clustered.
Added such cases to integration tests.

Clustering for models with deep layers.

---

tensorflow_model_optimization/python/examples/clustering/keras/mnist/mnist_cnn.py

Re-factor the clustering example for a better readability and overview. These changes were originally meant for #508 which had to be abandoned because of technical issues.

Re-factoring of the clustering example

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py

This reverts commit 7b7fe538640c484388dbce4390d126d57c070f91 (see PR #557 for discussion) that causes problems and was accidentally merged.

Revert "Small tidy up: Removed unused leftover variables."

---

tensorflow_model_optimization/python/core/api/clustering/keras/experimental/__init__.py
tensorflow_model_optimization/python/core/clustering/keras/BUILD
tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids_test.py
tensorflow_model_optimization/python/core/clustering/keras/experimental/BUILD
tensorflow_model_optimization/python/core/clustering/keras/experimental/cluster.py

**The changes**:
* Implemented the zero-centroid initialization for all clustering methods
* Implemented the sparsity masks for forward and backward propagation
* Added preserve_sparsity class member to ClusterWeights to make
sparsity preservation optional for all clustering methods
* Refactored AbstractCentroidsInitialisation to include zero-centroid
initialization for all init types
* Added unit tests around the new changes
**Description**: this PR introduces a feature called **Sparsity-Aware Clustering**
In the model optimization workflow, clustering typically follows pruning. Therefore, the clustering operation needs to ensure that the level of sparsity is not destroyed during the fine-tuning process.
To avoid sparsity degradation, we introduced two new operations:
1. We insert …

Add Anti Zero-Drift functionality for Sparsity-Aware clustering

---

RELEASE.md
tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py
tensorflow_model_optimization/python/core/clustering/keras/BUILD

This is a small fix to add a dependency on `clustering_callbacks.py` so that the file is added to the pip package.

Fix to add clustering_callbacks.py to the pip package

---

tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py

Fix typo and spacing for get_clustering_impl()

[Clustering]  Fix error message in clustering_registry.py

---

tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/BUILD
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/BUILD
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/__init__.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_quantize_registry.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_quantize_registry_test.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_utils.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/default_8bit_cluster_preserve_quantize_scheme.py
tensorflow_model_optimization/python/examples/cluster_preserve_qat/keras/BUILD
tensorflow_model_optimization/python/examples/cluster_preserve_qat/keras/mnist_cnn.py

This PR adds Cluster-preserving Quantization Aware Training (CQAT), which injects clustering trainable variables and corresponding TensorFlow ops into the original QAT Keras graph so that they could be trained together. In this way, the nice distribution of clustered weights can be kept after QAT, which gives benefits for model accuracy and compression rate.
Initial results:
| Model | Items | Baseline | Clustered Model | QATed Model | CQATed Model | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Mobilenet_v1 on CIFAR-10 | FP32 Top1 Accuracy | **94.88%**  | 94.48%  | (Fake INT8) 94.80% | (Fake INT8) 94.60% |
|                        | INT8 full integer quantization | 94.65% | **94.41%** | 94.77% | **94.52%** |
|                        | …

[Collaborative_optimizations] Cluster-preserving quantization aware training

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py

This PR adds a small test that demonstrates that keras custom layer is not supported for clustering.

[Clustering] Adding a small test for keras custom layer.

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py

- Added unit test that make sure that the functions trainable_weights() and non_trainable_weights() in tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py return the correct list of weights (e.g. both weights and centroids).
- Removed duplicated test: testClusterReassociation.
This is a follow-up PR to #575  based on [this comment](https://github.com/tensorflow/model-optimization/pull/575#issuecomment-713025610).

[Clustering] Adding a unit test to check all needed weights are returned by cluster_wrapper.

---

tensorflow_model_optimization/python/core/sparsity/keras/prune_integration_test.py

The sparsity after pruning wasn't correctly asserted in prune_integration_test.py: _check_strip_pruning_matches_original.
Fix #631

[Pruning] Fix pruning integration test bug

---

tensorflow_model_optimization/python/core/clustering/keras/BUILD
tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_config.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_distributed_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_algorithm.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py
tensorflow_model_optimization/python/core/clustering/keras/mnist_clusterable_layer_test.py
tensorflow_model_optimization/python/core/clustering/keras/mnist_clustering_test.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_quantize_registry.py

This PR is two fold: a new feature Average Gradient Aggregation and a cleaning of the clustering codebase.
Average Gradient Aggregation feature averages the gradient of each cluster centroid by the size of this cluster (the size being the number of child's weight belonging to the respective cluster).
We are letting users the choice between the existing implementation (Sum Gradient Aggregation) and the new implementation (Average Gradient Aggregation):
```python
tfmot.clustering.keras.cluster_weights(
to_cluster, number_of_clusters, cluster_centroids_init, cluster_gradient_aggregation=GradientAggregation.SUM
)
```
With cluster_gradient_aggregation being an enum: either `GradientAggregation.SUM` (default) or `GradientAggregation.AVG`.
With Sum Gradient Aggregation, the gradient of each …

[Clustering] Average Gradient Aggregation

---

tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_transforms.py

Not to copy the weights if bias is not used in the SeperableConv2D layer

Add check before setting bias of conv_weights in  SeparableConvQuantize

---

tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py
tensorflow_model_optimization/python/examples/clustering/keras/imdb/BUILD
tensorflow_model_optimization/python/examples/clustering/keras/imdb/imdb_gru.py
tensorflow_model_optimization/python/examples/clustering/keras/imdb/imdb_lstm.py
tensorflow_model_optimization/python/examples/clustering/keras/imdb/imdb_rnn.py

This PR enables the support of RNN layers in clustering.
Here is the current state of support for RNN:
| Type of RNN      | Status |
| ----------- | ----------- |
| RNNSimple      | ✅       |
| LSTM      | ✅       |
| GRU      | ✅       |
| PeepholeLSTM      | ❌       |
| BidirectionalRNN | ❌       |
| StackedRNN | ❌       |
To confirm that the implementation seems robust enough, we ran some experiments on the IMDB dataset and compared accuracies to the existing pruning implementation with a LSTM layer.
**Setup**: Direct pruning/clustering from random weight (no finetuning) for 3 epochs on the IMDB dataset. 0.7% sparsity for pruning or 16 clusters for clustering.
| Type of RNN      | Accuracy |
| ----------- | ----------- |
| **LSTM (pruning baseline)**      | **0.8485** |
| LSTM …

[Clustering] Enable RNN layers

---

tensorflow_model_optimization/python/core/clustering/keras/BUILD
tensorflow_model_optimization/python/core/clustering/keras/cluster_distributed_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/mnist_clustering_test.py

* small fix to stop centroids from drifting
* unit test coverage for fix
Summary of change:
Ensure the sparsity mask is updated during training time in sparsity-preserving clustering. Due to cluster-weight associations updates, the location of zero weights may change during training. This patch updated the sparsity mask according to such changes. It also adds extra tests to ensure sparsity aware clustering works during distributed training.

Fix for sparsity-preserving clustering

---

tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/BUILD
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_integration_test.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_quantize_registry.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_quantize_registry_test.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_utils.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/default_8bit_cluster_preserve_quantize_scheme.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/mnist_prune_cluster_preserve_qat_test.py

This PR adds support for Pruning-Clustering-preserving Quantization Aware Training (PCQAT). Aiming at preserving the sparsity and unique weights in the output optimized model, fixed pruning masks and the stochastic updates of clustering training variables are enabled during quantization-aware training.
User API:
```
preserve_sparsity = True
quant_aware_annotate_model = quantize.quantize_annotate_model(pruned_clustered_model)
pcqat_model = quantize.quantize_apply(
quant_aware_annotate_model,
scheme=default_8bit_cluster_preserve_quantize_scheme
.Default8BitClusterPreserveQuantizeScheme(preserve_sparsity))
```
Main changes:
- cluster_preserve_integration_test: edge cases (e.g. passing non-pruned models, passing models with uniform weights, etc.), checks for the updates of trainable variables …

[Collaborative optimization] Pruning-Clustering-preserving Quantization Aware Training

---

RELEASE.md

In this PR we update release notes for clustering for the future release of tfmot.

Updated release notes with clustering items.

---

tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py
tensorflow_model_optimization/python/examples/clustering/keras/imdb/BUILD
tensorflow_model_optimization/python/examples/clustering/keras/imdb/imdb_multiple_cells.py
tensorflow_model_optimization/python/examples/clustering/keras/imdb/imdb_utils.py

This PR adds support for StackedRNNCells, PeepholeLSTMCell, and Bidirectional in clustering. To verify the implementation, unit tests and end-to-end tests are provided in the PR.
Below are numbers generated using the imdb_multiple_cells.py. In those experiments, the clustering wrapper was applied to a model with randomly initialized weights for 1 epoch on the IMDB dataset with a number of clusters equal to 16.
| Types of RNN layers/Cells 	| Experimental setups                               	| Accuracy in clustering experiments 	|
|---------------------------	|---------------------------------------------------	|------------------------------------	|
| StackedRNNCell            	|Two LSTMCells wrapped by a StackedRNNCell | 0.8502                             	|
| PeepholeLSTMCell …

[Clustering] Add the layer support for StackedRNNCells, PeepholeLSTMCell, and Bidirectional.

---

tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_algorithm.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py
tensorflow_model_optimization/python/core/clustering/keras/experimental/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/mnist_clustering_test.py

This PR extends the clustering implementation to include support for per-channel clustering of Conv2D layers.
The current clustering API allows for restricting the unique number of weights of a layer to a maximum given value. For the time being, this is done on a per-layer basis for all supported operators, including Conv2D layers. 
This PR implements the changes necessary in the clustering flow to enable per-channel clustering for Conv2D layers, in which the whole weight kernel is not clustered as one, but the channels in it are treated separately, so that each of them has the requested number of unique weights. 
This would improve the performance of Conv2D layers as it is less restrictive and would increase the representation power achievable by the convolution weight kernel. This is …

Per-channel Clustering Implementation and Tests

---

tensorflow_model_optimization/python/core/api/BUILD
tensorflow_model_optimization/python/core/quantization/keras/experimental/BUILD

This PR fixes import issues seen.
When trying the following: 
`import tensorflow_model_optimization as tfmot`
the following error occurs: 
`ModuleNotFoundError: No module named 'tensorflow_model_optimization.python.core.quantization.keras.experimental'`

Fix for tensorflow_model_optimization import error

---

tensorflow_model_optimization/g3doc/guide/pruning/index.md
tensorflow_model_optimization/g3doc/guide/pruning/pruning_with_sparsity_2_by_4.ipynb

This PR adds 
- description of the structural pruning (M by N) to the pruning overview document
- a small tutorial that demonstrates how this structural pruning should be used
The tutorial uses a simple cnn model on MNIST dataset, where `Cond2D` layer and `Dense` layers are pruned with structural pruning. The model is converted to TFLite file and weights of these layers are visualize to demonstrate the pattern of structural pruning 2 by 4.

[Pruning, sparsity 2 by 4 documentation]

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_algorithm.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_registry_test.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_integration_test.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_quantize_registry.py

This PR extends the existing functionality for the CQAT and PCQAT to work with the models that has been clustered using the [clustering per channel technique](https://github.com/tensorflow/model-optimization/pull/871).
<h3>Overview</h3>
The accuracy of the model in the optimization pipeline: clustering -> quantization can be improved by using the clustering per channel. Applying CQAT or PCQAT can improve accuracy further for the quantized model at the same time keeping the number of clusters and level of sparsity. The current PR allows to keep the number of clusters per channel if the model is clustered this way. 
<h3>API changes</h3>:
We don't change any APIs as we deduce whether the clustered per channel has been used based on the provided clustered model.
<h3>Testing results</h3> …

Support of clustering per channel in (P)CQAT.

---

tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids.py
tensorflow_model_optimization/python/core/clustering/keras/clustering_centroids_test.py

When the data_format is 'channels_first', clustering per channel is not working correctly due to mismatch in arguments.
This CR fixed this case + added test that we set the argument correctly.
The reported bug is https://github.com/tensorflow/model-optimization/issues/939

Fix for the bug with data_format in clustering per channel

---

tensorflow_model_optimization/g3doc/_index.yaml

The main page on model optimizations on tensorflow.org 
https://www.tensorflow.org/model_optimization
is missing the link to the released blogpost on collaborative techniques: https://blog.tensorflow.org/2021/10/Collaborative-Optimizations.html
This PR adds the missing link.

Added missing link to blogpost on collaborative technique.

---

tensorflow_model_optimization/g3doc/guide/clustering/index.md

It seems that the two indentations for the "Full (all Conv2D layers)" sections in the results table miss the appropriate indentation.

Fix missing indentation in html table

---

tensorflow_model_optimization/python/core/clustering/keras/cluster.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_integration_test.py
tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_integration_test.py
tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve/cluster_preserve_quantize_registry.py

* Root cause of issue was that per-channel clustering was being performed on a Conv2D layer with less weights per channel than the number of desired clusters per channel, leading to 1 clustered weight per channel in the resulting model
* Desired behaviour is that no clustering should occur in this scenario
* Behaviour also corrected to not perform clustering if too few weights in the cluster_per_channel=False scenario
* Warnings now given to user that a Conv2D passed to the clustering API had too few weights for the requested type of clustering and that no clustering was performed on it.
* ValueError given if layer passed to clustering API with no weights
Change-Id: Idee3388e4905b5bf41f9598fa49ce200e9682bc6

Fixes for GitHub Issue #979
